name: get kubectl binary

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]


env:
  KUBECTL_VERSION: "1.22.11"
  KUBECTL_SHA256: "a61c697e3c9871da7b609511248e41d9c9fb6d9e50001425876676924761586b"
  KUBECTL_IMAGE: ghcr.io/${{ github.repository }}

jobs:

  image:
    runs-on: ubuntu-latest
    name: build and push image
    steps:
    - uses: docker/login-action@v2
      name: login to ghrc.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
          KUBECTL_SHA256=${{ env.KUBECTL_SHA256 }}
        tags: ${{ env.KUBECTL_IMAGE }},${{ env.KUBECTL_IMAGE }}:${{ env.KUBECTL_VERSION }}
