name: get kubectl binary

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

env:
  KUBECTL_VERSION: "1.29.1"

jobs:
  image:
    if: "!contains(github.event.commits[0].message, 'skip:kubectl')"
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: build and push image
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        build-args: |
          VERSION=${{ env.KUBECTL_VERSION }}
        tags: ghcr.io/${{ github.repository }},ghcr.io/${{ github.repository }}:${{ env.KUBECTL_VERSION }}