name: get kubectl binary

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

env:
  KUBECTL_VERSION: "1.26.3"
  KUBECTL_SHA256: "026c8412d373064ab0359ed0d1a25c975e9ce803a093d76c8b30c5996ad73e75"
  KUBECTL_IMAGE: ghcr.io/${{ github.repository }}

jobs:

  image:
    runs-on: ubuntu-latest
    name: build and push image
    steps:
    - uses: docker/login-action@v2
      name: login to ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
          KUBECTL_SHA256=${{ env.KUBECTL_SHA256 }}
        tags: ${{ env.KUBECTL_IMAGE }},${{ env.KUBECTL_IMAGE }}:${{ env.KUBECTL_VERSION }}
